#! /usr/bin/env bash

# also, to facilitate deployment to s3 on push, add a shell script to
# .git/hooks/pre-push containing:
# ./deploy-to-s3

echo "pushing to S3..."
dotclean.js .
aws s3 sync --profile "bretton.wade@gmail.com" . s3://aws-website-brettonw-8xhbv --delete --exclude "*" --include "*.html" --include "github/*" --include "css/*" --include "js/*" --include "img/*" --include "projects/*" --include "musings/*" --include "turnips/*" --acl public-read


echo "invalidating distribution to force cache refresh...";
aws cloudfront create-invalidation --profile "bretton.wade@gmail.com" --distribution-id E1IOU9BOQX6LTO --paths "/*"
